name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get install -y clang-11 ninja-build libexpected-dev libbenchmark-dev

    - name: Configure CMake
      env:
        CC: /usr/bin/clang-11
        CXX: /usr/bin/clang++-11
        CMAKE_GENERATOR: Ninja
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: ninja -C ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./test/pmql_test     
