name: Sphinx

on:
  workflow_run:
    workflows: [CMake]
    branches: [master]
    types:
    - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: master
    
    - name: Install dependencies
      run: |
          sudo apt-get install -y \
            clang-11 \
            ninja-build \
            doxygen \
            python3-sphinx \
            python3-sphinx-rtd-theme \
            python3-breathe \
            libbenchmark-dev \

    - name: Configure CMake
      env:
        CC: /usr/bin/clang-11
        CXX: /usr/bin/clang++-11
        CMAKE_GENERATOR: Ninja
      run: cmake -B ${{github.workspace}}/master/build

    - name: Build documentation
      run: ninja -C ${{github.workspace}}/master/build sphinx

    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
      
    - name: Commit and push gh-pages
      run: |
          cd ${{github.workspace}}/gh-pages
          mv ${{github.workspace}}/master/build/docs/sphinx/* .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update documentation"
          git push
      
